name: build-branch

on:
  push:
    branches-ignore:
      - 'develop'

jobs:
  build-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        id: extract_branch
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | sed -e 's/\//_/g')"
          echo "::set-output name=sha_short::$(echo ${GITHUB_SHA::10})"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Whitesource Action
        uses: TheAxZim/Whitesource-Scan-Action@v1.0.0
        with:
          wssURL: https://saas.whitesourcesoftware.com/agent
          apiKey: ${{ secrets.WSS_API_KEY }}
          productName: 'maas'
          projectName: 'maas-pubsubplus-configs'

      - name: Set Release version env variable
        run: |
          echo "RELEASE_VERSION=${{ steps.extract_branch.outputs.branch }}-${{ steps.extract_branch.outputs.sha_short }}" >> $GITHUB_ENV

      - name: Build and Publish package
        run: gradle -Pversion="${{ env.RELEASE_VERSION }}-SNAPSHOT" build publish
        env:
          GITHUB_USERNAME: ${{ secrets.PACKAGES_ADMIN_USER }}
          GITHUB_TOKEN: ${{ secrets.PACKAGES_ADMIN_TOKEN }}